apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  namespace: bioc-code-explorer
  name: bioc-code-tools-index-pvc
spec: 
  storageClassName: "basic-csi"
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 20Gi 
