apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  namespace: bioc-code-explorer
  name: bioc-code-tools-shared-info-pvc
spec: 
  storageClassName: "basic-csi"
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi 
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  namespace: bioc-code-explorer
  name: application-pvc
spec: 
  storageClassName: "basic-csi"
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 50Gi 
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  namespace: bioc-code-explorer
  name: nginx-logs
spec: 
  storageClassName: "basic-csi"
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 10Gi 