apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  namespace: bioc-nginx-test
  name: bioc-code-tools-shared-info-pvc
spec: 
  storageClassName: "basic-csi"
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 1Gi 
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  namespace: bioc-nginx-test
  name: application-pvc
spec: 
  storageClassName: "basic-csi"
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 1Gi 

