apiVersion: batch/v1
kind: CronJob
metadata:
  name: index-git-repo
  namespace: bioc-code-explorer
spec:
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: git-repo
                  topologyKey: "kubernetes.io/hostname"
          containers:
          - name: index-git-repo
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 700m
                memory: 1Gi
            imagePullPolicy: Always
            image: grimbough/code.bioc-mirror-updater:0.1.1
            env:
            - name: CONTAINER_ZOEKT_IDX_DIR
              value: "/var/zoekt"
            - name: GIT_REPOS_DIR
              value: "/var/git"
            volumeMounts:
            - mountPath: /var/zoekt
              name: git-index
            - mountPath: /var/git
              name: git-repos
          initContainers:
          - name: volume-mount-hack
            resources:
              limits:
                cpu: 1
                memory: 1Gi
              requests:
                cpu: 700m
                memory: 800Mi
            image: busybox
            command: ["sh", "-c", "chown -R 82:82 /var/git /var/zoekt"]
            volumeMounts:
            - name: git-repos
              mountPath: /var/git
          volumes:
          - name: git-index
            persistentVolumeClaim:
              claimName: bioc-code-tools-index-pvc
          - name: git-repos
            persistentVolumeClaim:
              claimName: bioc-code-iscsi-pvc
          restartPolicy: Never
