apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-logrotate-signal
  namespace: bioc-code-explorer
spec:
  schedule: "0 0 * * *"  # Daily at midnight
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          securityContext:
            fsGroup: 101
          serviceAccountName: logrotate-signal-sa
          containers:
            - name: signal-nginx
              image: grimbough/code.bioc-logrotate:0.0.1
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: "/var/log/nginx"
                  name: nginx-logs
              command:
                - /bin/sh
                - -c
                - |
                  logrotate --verbose --force --state=/tmp/logroate_tmp /etc/logrotate.d/nginx
                  sleep 1;
                  POD=$(kubectl get pods -l app=git-repo -o jsonpath='{.items[0].metadata.name}')
                  kubectl exec $POD -c nginx -- kill -USR1 1
                  kubectl exec $POD -c goaccess -- kill -USR1 1
                  POD2=$(kubectl get pods -l app=code-home -o jsonpath='{.items[0].metadata.name}')
                  kubectl exec $POD2 -c code-home -- kill -USR1 1
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
                runAsUser: 101
                runAsGroup: 101
                allowPrivilegeEscalation: false
                capabilities:
                  drop: 
                  - ALL
          restartPolicy: OnFailure
          volumes:
            - name: nginx-logs
              persistentVolumeClaim:
                claimName:  nginx-logs
