apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-repo
  namespace: bioc-code-explorer
spec:
  ingressClassName: "external-users"
  rules:
  - host: code.bioconductor.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-home
            port: 
              name: http
      - path: /browse
        pathType: Prefix
        backend:
          service:
            name: git-repo
            port: 
              name: http
      - path: /logs
        pathType: Prefix
        backend:
          service:
            name: git-repo
            port: 
              name: http
  tls:
  - hosts:
    - code.bioconductor.org
  - secretName: certs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zoekt-search
  namespace: bioc-code-explorer
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "global-stripprefix@file"
spec:
  ingressClassName: "external-users"
  rules:
  - host: code.bioconductor.org
    http:
      paths:
      - path: /search
        pathType: Prefix
        backend:
          service:
            name: zoekt-search
            port: 
              name: http
  tls:
  - hosts:
    - code.bioconductor.org
  - secretName: certs

