apiVersion: v1
kind: ServiceAccount
metadata:
  name: logrotate-signal-sa
  namespace: bioc-code-explorer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logrotate-signal-role
  namespace: bioc-code-explorer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logrotate-signal-binding
  namespace: bioc-code-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logrotate-signal-role
subjects:
  - kind: ServiceAccount
    name: logrotate-signal-sa
